name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
        timeout-minutes: 10

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test reports
          path: '**/build/test-results/**/TEST-*.xml'
          reporter: java-junit

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    timeout-minutes: 10
    needs: [ gradle-build ]
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: 🤖 Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          target: minor
          merge-method: squash
